### PR TITLE
refactor: transition to reStructuredText 

### PR DESCRIPTION
**Pull request by dviererbe**
This PR transitions from markdown to reStructuredText 

> [!NOTE]
> It started out as proposals/experiments how the documentation could be structured.

### CODE REVIEW

**Comment by dviererbe** [comment]
My hope was the ReadTheDocs would build this branch, but unfortunately it does not. Here is a screenshot how it would look like:

image

**Comment by dviererbe** [comment]
CC: @rkratky

**Comment by dviererbe** [comment]
I tinkered a little bit more and added logos:
image

**Comment by dviererbe** [comment]
ReadTheDocs built a preview :)
https://canonical-ubuntu-for-developers--3.com.readthedocs.build/en/3/

**Comment by dviererbe** [comment]
The spellcheck failure is a known problem, see https://github.com/canonical/canonical-sphinx/issues/27. A fix is in the working.

**Comment by rkratky** [comment]
Hey @dviererbe, this is pretty awesome. Thanks for taking the time to do this. You beat me to it, but I wanted to file indiv. work items for this effort that would also outline the desired structure. See https://warthogs.atlassian.net/browse/FR-6855

While I really like the way you set it up, I'm thinking: will this reflect the learning path we want for devs? In my view, the most important stuff is the generic set up that a prospective dev needs to do in order to turn their vanilla Ubuntu install into a dev workstation.

The focus is not necessarily on the indiv. toolchains (as the proposed structure suggests) but on the common tasks that need to happen. This, of course, needs to be followed up by specific instructions pertaining to the various toolchains.

So, I see a number of ways to address this:

1. Keep the structure as you proposed, and include a generic set-up article in each. This would need to be a single-sourced topic that would probably only diverge minimally between the toolchains. Chances are, more than one generic topic would need to be covered in this way (version control, IDEs, debugging, ...).
    * pros: It's straightforward and pbbly easy to navigate.
    * cons: I see a big potential for hard-to-maintain single-sourcing logic or content duplication.
2. Change the structure to focus on setting up a dev workstation (i.e. only a single set of Diataxis categories) and include how-to articles for indiv. toolchains to cover their specific needs.
    * pros: Seems to better address the overall use case (compare: "Ubuntu Desktop is a great dev workstation, this is how you set it up and use all these toolchains on it." vs. "There are a bunch of toolchains shipped with Ubuntu Desktop. This is how to use them."). Less content overall, i.e. lighter development + maintenance burden
    * cons: Perhaps slightly less straightforward when it comes navigation.

**Comment by rkratky** [comment]
> I tinkered a little bit more and added logos

I'm afraid this is a bit overboard :) If we include logos, we need to:

- Make them much smaller, so as not to overwhelm the front page.
- Use transparent-background images top accommodate the dark theme.
- Ensure all resources are properly attributed and use a compatible license.

**Comment by rkratky** [comment]
> ReadTheDocs built a preview :) https://canonical-ubuntu-for-developers--3.com.readthedocs.build/en/3/

Was this not built automatically? If so, that would indicate some problem in the RTD set up, but I'm seeing any (unexpected) errors there.

**Comment by dviererbe** [comment]
@rkratky 

> 1. [...] include a generic set-up article in each. This would need to be a single-sourced topic that would probably only diverge minimally between the toolchains. Chances are, more than one generic topic would need to be covered in this way (version control, IDEs, debugging, ...).
>    - [...]
>    - cons: I see a big potential for hard-to-maintain single-sourcing logic or content duplication.

This are really good points that this is not the optimal structure. I suppose we could use [sphinx-tabs](https://canonical-documentation-with-sphinx-and-readthedocscom.readthedocs-hosted.com/style-guide/#tabs) (see also: https://github.com/canonical/ubuntu-packaging-guide/discussions/30#discussioncomment-8050723), which has the ability to keep the selected tab value between pages. This way we have one common structure, but if developers select the toolchain they are interested in they only see the content for this toolchain consistent between pages. This still makes toolchain specific articles stick out.

Also my hope with the proposed structure was that we could set [Code Owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), but with a common structure, this is difficult. We could put all the toolchain specific paragraphs in seperate files and use the [include feature](https://canonical-documentation-with-sphinx-and-readthedocscom.readthedocs-hosted.com/style-guide/#file-inclusion).

We could also use the include feature to de-duplicate content. If we would want 1. to work.

> > I tinkered a little bit more and added logos
>
> I'm afraid this is a bit overboard :) [...]

Agree, it is in it's current state distracting

> > ReadTheDocs built a preview :) https://canonical-ubuntu-for-developers--3.com.readthedocs.build/en/3/
> 
> Was this not built automatically? If so, that would indicate some problem in the RTD set up, but I'm seeing any (unexpected) errors there.

I set the flag to build PR's after I opened mine. It built #2 but not mine after that, so I thought that mine does not get build, because it is an external repo, but now it did, so everything seems fine 👍🏻

**Comment by rkratky** [comment]
> I suppose we could use [sphinx-tabs](https://canonical-documentation-with-sphinx-and-readthedocscom.readthedocs-hosted.com/style-guide/#tabs) (see also: [canonical/ubuntu-packaging-guide#30 (comment)](https://github.com/canonical/ubuntu-packaging-guide/discussions/30#discussioncomment-8050723)), which has the ability to keep the selected tab value between pages. This way we have one common structure, but if developers select the toolchain they are interested in they only see the content for this toolchain consistent between pages. This still makes toolchain specific articles stick out.

That's a great idea! Only potential downside might be that there are quite a few of the toolchains already and more may be coming. Not sure how that would render if the tabs started to spill over more than one line. I'll need to test this.

> Also my hope with the proposed structure was that we could set [Code Owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), but with a common structure, this is difficult. We could put all the toolchain specific paragraphs in seperate files and use the [include feature](https://canonical-documentation-with-sphinx-and-readthedocscom.readthedocs-hosted.com/style-guide/#file-inclusion).

Yep. The indiv. tabs could use 'include'. That way, the structure of the tabbed page wouldn't get crazy, and the indiv. toolchain-specific files could have different owners.

**Comment by rkratky** [comment]
@dviererbe Please, let me know if you're going to be able to work on this. I'd be happy to take over if needed -- most of the work has already been done in your submission and in this discussion :) Btw, I suppose this would be a part of https://warthogs.atlassian.net/browse/FR-7995 -- if necessary, please, add your notes there.

**Comment by dviererbe** [comment]
@rkratky did you mean this, or assemble a list of articles we want to work on first?

### Proposal 1: Using Tabs  

#### Live Demo
https://canonical-ubuntu-for-developers--3.com.readthedocs.build/en/3/tutorial/hello-world_with-tabs/

#### Screenshot
image

### Proposal 2: Using the TOC tree

#### Live Demo
https://canonical-ubuntu-for-developers--3.com.readthedocs.build/en/3/tutorial/hello-world/

#### Screenshot
image

### Remarks

- Tabs have the advantage that they are much more condensed
- The TOC tree scales better (IMHO) and allows to link to a specific article, which is apparently not possible with tabs

After experimenting, I would prefer Proposal 2 (Using the TOC tree).

**Comment by rkratky** [comment]
> @rkratky did you mean this, or assemble a list of articles we want to work on first?

I meant the PR in general :)

Indiv. articles are tracked in:

- https://warthogs.atlassian.net/browse/FR-6973
- https://warthogs.atlassian.net/browse/FR-6976

> After experimenting, I would prefer Proposal 2 (Using the TOC tree).

I agree, though the tabs are so much prettier :/

**Comment by dviererbe** [comment]
This will not get merged, but let me write down my closing thoughts why I still think that using reStructuredText makes more sense than using "markdown".

1. We don't use markdown, we use MyST which is a superset of markdown. The reason that I highlight that is that it actually transforms into reStructuredText. Therefore, anyone who wants to contribute to this documentation still has to learn reStructuredText. So, why not use reStructuredText then?
2. MyST looks verbose. Don't get me wrong, reStructuredText does not win any beauty contest either, but please look no further than the index:

`````md
````{grid} 1 1 2 2
```{grid-item-card} [Tutorial](/index)
:link: tutorial/index
:link-type: doc
**Get started** - hands-on introduction to developing on Ubuntu Desktop for new users
```
```{grid-item-card} [How-to guides](/index)
:link: howto/index
:link-type: doc
**Step-by-step guides** covering key operations and common tasks
```
````

````{grid} 1 1 2 2
:reverse:
```{grid-item-card} [Reference](/index)
:link: reference/index
:link-type: doc
**Explanations** - conceptual information
```
```{grid-item-card} [Explanation](/index)
:link: explanation/index
:link-type: doc
**Discussion and clarification** of key topics
```
````
`````

And now look at the reStructuredText equivalent:

```rst
.. grid:: 1 1 2 2
   :gutter: 3

   .. grid-item-card:: **Tutorial**
       :link: tutorial/index
       :link-type: doc

       **Get started** - hands-on introduction to developing on Ubuntu Desktop 
       for new users

   .. grid-item-card:: **How-to guides**
       :link: howto/index
       :link-type: doc

       **Step-by-step** covering key operations and common tasks

   .. grid-item-card:: **Reference**
       :link: reference/index
       :link-type: doc

       **Explanations** - conceptual information

   .. grid-item-card:: **Explanation**
       :link: explanation/index
       :link-type: doc

       **Discussion and clarification** of key topics
```

I can't be the only one that gets the impression that the markdown version looks like someone had a stroke while writing this. This is the perfect breeding ground for hard to catch formatting errors. Additionally this feels like writing LISP, but instead of counting `(`, `)`, you have to count your `` ` ``.

**Comment by rkratky** [comment]
@dviererbe As mentioned elsewhere, I understand your sentiment. A couple of notes:

> anyone who wants to contribute to this documentation still has to learn reStructuredText

Not necessarily. The complex stuff is only used for TOCs and similar. When contributing basic content, such as a new article, MarkDown is sufficient. There's no need to understand rST.

> MyST looks verbose

Perhaps not verbose but clunky. I agree. But i'll be adding support for [colon fences](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#code-fences-using-colons), which makes the above look like this:

```markdown
:::{grid-item-card} [Tutorial](/index)
:link: tutorial/index
:link-type: doc
**Get started** - hands-on introduction to developing on Ubuntu Desktop for new users
:::

:::{grid-item-card} [How-to guides](/index)
:link: howto/index
:link-type: doc
**Step-by-step guides** covering key operations and common tasks
:::
```

I think that's better :)

**Pull request closed without merging**
